### ISSUE TITLE
Project is missing a license file

### ISSUE THREAD

**Issue by mcroydon** [lmika/oaipmh#3]
This project lacks a LICENSE file, or an indication of what license this project is released under. This is helpful so that people can know how they can or can't use your software.

[This GitHub help page](https://help.github.com/articles/open-source-licensing/) has more information and [choosealicense.com](http://choosealicense.com/) can help you select one if you don't have a strong preference.

**Comment by lmika-bom** [comment]
Have added the MIT licence to README.md.  Will need to follow-up on the appropriate copyright holder for the work though.
